### ISSUE TITLE
Can't install operator

### ISSUE THREAD

**Issue by pikodd** [openshift-kni/performance-addon-operators#928]
I'm installing the operator in OKD using 
`CLUSTER=manual make cluster-deploy` command
And I'm getting error in Install Plan
`error validating existing CRs against new CRD's schema for "performanceprofiles.performance.openshift.io": error listing resources in GroupVersionResource schema.GroupVersionResource{Group:"performance.openshift.io", Version:"v1", Resource:"performanceprofiles"}: conversion webhook for performance.openshift.io/v2, Kind=PerformanceProfile failed: Post "https://performance-operator-service.openshift-performance-addon-operator.svc:443/convert?timeout=30s": service "performance-operator-service" not found`

I manually created the service, like in [Node Tuning Operator](https://github.com/openshift/cluster-node-tuning-operator/blob/master/manifests/45-webhook-configuration.yaml)
```
kind: Service
apiVersion: v1
metadata:
  name: performance-operator-service
  namespace: openshift-performance-addon-operator
  labels:
    name: performance-operator-service
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1654682539
    service.beta.openshift.io/serving-cert-secret-name: performance-addon-operator-webhook-cert
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1654682539
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: '443'
      protocol: TCP
      port: 443
      targetPort: 4343
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: performance-operator

```

and where is another error 
`error validating existing CRs against new CRD's schema for "performanceprofiles.performance.openshift.io": error listing resources in GroupVersionResource schema.GroupVersionResource{Group:"performance.openshift.io", Version:"v1", Resource:"performanceprofiles"}: conversion webhook for performance.openshift.io/v2, Kind=PerformanceProfile failed: Post "https://performance-operator-service.openshift-performance-addon-operator.svc:443/convert?timeout=30s": no endpoints available for service "performance-operator-service"`

I checked the endpoints, and I found nothing. 

```
# oc get endpoints 
NAME                           ENDPOINTS   AGE
performance-operator-service   <none>      76s

```
Also, no Deployments and Pods were created.

OKD, OC and K8s version
```
Client Version: 4.10.0-0.okd-2022-05-07-021833
Server Version: 4.10.0-0.okd-2022-05-07-021833
Kubernetes Version: v1.23.5-rc.0.2068+b463d71c3d5ca3-dirty
```

How it can be resolved?
